### ISSUE TITLE
WFIRST module accuracy parameters

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#661]
This is an issue that should be addressed before we tag v1.3:

It seems that there are some numerical inaccuracies in the rendering of PSFs in the WFIRST module, apparently related to the default Fourier-space sampling.  As I understand it, the Fourier-space sampling for optical PSFs is chosen based on the obscured Airy, but if there are struts then one might need better sampling.  Some tests seem to confirm that the sampling is adequate if we remove the struts, and problems only arise with struts.  The fix for this problem differs depending on whether approximate struts are used or the full pupil plane image is used.

I will put some more plots and comments soon, but I'm mainly opening this not terribly informative issue now to flag the fact that there is one more thing to do before tagging v1.3.

**Comment by rmandelb** [comment]
@arunkannawadi - I was trying to put together a simple script that demonstrates this issue without directly using the WFIRST module (since it should be possible to show using OpticalPSfs, where we have more control over the choice of adding aberrations / struts / whatever) - but my simple script does not seem to demonstrate it well.  Do you have a simple script that demonstrates this?  Is it in a repository that I can access?

**Comment by arunkannawadi** [comment]
@rmandelb, I don't have a script as I was just playing around with them in
the terminal directly. I will consolidate them all and put in a script.

On Wed, Apr 29, 2015 at 10:33 PM, Rachel Mandelbaum <
notifications@github.com> wrote:

> @arunkannawadi <https://github.com/arunkannawadi> - I was trying to put
> together a simple script that demonstrates this issue without directly
> using the WFIRST module (since it should be possible to show using
> OpticalPSfs, where we have more control over the choice of adding
> aberrations / struts / whatever) - but my simple script does not seem to
> demonstrate it well. Do you have a simple script that demonstrates this? Is
> it in a repository that I can access?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GalSim-developers/GalSim/issues/661#issuecomment-97636929>
> .
>



-- 
Regards

Arun Kannawadi Jayaraman
PhD candidate, Dept. of Physics,
Carnegie Mellon University,
Pittsburgh, PA 15213

**Comment by rmandelb** [comment]
Thanks, please do.

**Comment by arunkannawadi** [comment]
@rmandelb, I have shared the script with you. The script generates the MTF
for many different simpler PSFs for comparison. You can turn-off those by
setting ```draw_simple_profiles=True```. Further, it goes on to generate
the WFIRST PSF with and without the pupil plane and then I have cherry
picked from the WFIRST code to directly call the OpticalPSF routine. You
can comment out the unnecessary PSF calls if you're not interested in them.
Note that this still needs the WFIRST module as it stands, but it is not
hard to totally get rid of any reference to WFIRST. The MTFs of the PSFs
are stored as a .npy file for later use and it also pops out the plot
immediately.

I found something little weird. Was anything changed in the PSFs module
recently, either the optics.py or wfirst_psfs.py? The ringing has reduced
in the latest version of galsim but if I revert back to some of the earlier
versions, the ringing does increase!

On Thu, Apr 30, 2015 at 8:27 PM, Rachel Mandelbaum <notifications@github.com
> wrote:

> Thanks, please do.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GalSim-developers/GalSim/issues/661#issuecomment-98008051>
> .
>



-- 
Regards

Arun Kannawadi Jayaraman
PhD candidate, Dept. of Physics,
Carnegie Mellon University,
Pittsburgh, PA 15213

**Comment by arunkannawadi** [comment]
The script also uses scipy, btw, for 2-D FFTs.

On Fri, May 1, 2015 at 2:04 PM, Arun Kannawadi <arunkannawadi@cmu.edu>
wrote:

> @rmandelb, I have shared the script with you. The script generates the MTF
> for many different simpler PSFs for comparison. You can turn-off those by
> setting ```draw_simple_profiles=True```. Further, it goes on to generate
> the WFIRST PSF with and without the pupil plane and then I have cherry
> picked from the WFIRST code to directly call the OpticalPSF routine. You
> can comment out the unnecessary PSF calls if you're not interested in them.
> Note that this still needs the WFIRST module as it stands, but it is not
> hard to totally get rid of any reference to WFIRST. The MTFs of the PSFs
> are stored as a .npy file for later use and it also pops out the plot
> immediately.
>
> I found something little weird. Was anything changed in the PSFs module
> recently, either the optics.py or wfirst_psfs.py? The ringing has reduced
> in the latest version of galsim but if I revert back to some of the earlier
> versions, the ringing does increase!
>
> On Thu, Apr 30, 2015 at 8:27 PM, Rachel Mandelbaum <
> notifications@github.com> wrote:
>
>> Thanks, please do.
>>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/GalSim-developers/GalSim/issues/661#issuecomment-98008051>
>> .
>>
>
>
>
> --
> Regards
>
> Arun Kannawadi Jayaraman
> PhD candidate, Dept. of Physics,
> Carnegie Mellon University,
> Pittsburgh, PA 15213
>



-- 
Regards

Arun Kannawadi Jayaraman
PhD candidate, Dept. of Physics,
Carnegie Mellon University,
Pittsburgh, PA 15213

**Comment by rmandelb** [comment]
> The ringing has reduced in the latest version of galsim but if I revert back to some of the earlier
> versions, the ringing does increase!

Can you specify an earlier version that works, and I will try to figure out what happened?
Can you clarify, is the ringing now sufficiently small that it's below the level we wanted?  Are we talking about a change from the 1% level to 0.1% or 0.01% or ...?

**Comment by arunkannawadi** [comment]
Sorry, the culprit is none other than me! I was comparing the results run on my local machine where I have tweaked with the GalSim code to reduce the ringing with those run on the cluster which has v1.2 of GalSim. This is what you should find if you run the script using the default values (see image in github page)

![mtf_4galsim](https://cloud.githubusercontent.com/assets/5103390/7435728/3d0e8440-f014-11e4-82ec-9eb6d875cb4e.png)

With my local version of galsim, the value of MTF does go beyond 10^-3 for high frequencies ( k-index ~ 100 ) even after tweaking the oversampling rate and this is not good enough for IMCOM. Moreover, this tweak works only for PSFs without the exact pupil plane. How to reduce the ringing for PSF images with the exact pupil plane is the issue here.

**Comment by rmandelb** [comment]
> I have shared the script with you. 

Where?

> tweaked with the GalSim code to reduce the ringing 

How?  Is this what you wrote on your wiki page?

**Comment by rmandelb** [comment]
Okay, I think I have something that works.  @arunkannawadi , please check this out and see what you think.

My baseline was to look at the monochromatic MTF for H158 at its effective wavelength with approximate struts and the full pupil plane.   2d MTF with approximate struts:
![fig1_6_before](https://cloud.githubusercontent.com/assets/1454906/7926967/73f61a9e-08a7-11e5-8338-1d11f88c9006.png)
and full pupil plane:
![fig1_5_before](https://cloud.githubusercontent.com/assets/1454906/7926971/8be9c808-08a7-11e5-8078-e645eeeb9483.png)

Yuck.

I made the following modifications:
* with approximate struts, I set oversampling to 3.
* without approximate struts, I simply added a 2x border around the pupil plane image and set oversampling to 2.

I then get the following 2d MTF with approximate struts:
![fig1_6_after](https://cloud.githubusercontent.com/assets/1454906/7926977/ab700d54-08a7-11e5-8ee7-b79194daf69b.png)
and with full pupil plane:
![fig1_5_after](https://cloud.githubusercontent.com/assets/1454906/7926980/b40b5126-08a7-11e5-8284-7dc87ec9ad0f.png)

These are not perfect, but much cleaner.  For example, for the latter, here's the 1d slice at fixed k_y=0:
![fig2_5_after](https://cloud.githubusercontent.com/assets/1454906/7926984/c5b9c380-08a7-11e5-83c4-b7c371a0eaec.png)
The bumps have an amplitude of a few x 10^-4 at most, whereas before they had an amplitude of 10^-2.

What do you think?  I'm going to push a branch that has this as an optional setting with a warning that it's slower and more expensive in terms of RAM than the default.

**Comment by rmandelb** [comment]
FYI I pushed a commit that does this with a single keyword to getPSF (```high_accuracy```), and you should find that your MTF_analysis script reproduces these plots.  Unless there are any concerns, I will make a PR so we can get this merged, and tag GalSim v1.3, which I think was waiting only on this.

**Comment by arunkannawadi** [comment]
In my playing around on this problem earlier, I do remember seeing such
images. In particular, the 1-D slice with secondary peaks going a little
above 10^-4. From what I understood from @chazshapiro, this is still not
okay. IMCOM cannot handle this PSF unless the stringent requirement that
the images have to be band limited, which Chaz is planning to work on in
the near future.

On Monday, June 1, 2015, Rachel Mandelbaum <notifications@github.com> wrote:

> FYI I pushed a commit that does this with a single keyword to getPSF (
> high_accuracy), and you should find that your MTF_analysis script
> reproduces these plots. Unless there are any concerns, I will make a PR so
> we can get this merged, and tag GalSim v1.3, which I think was waiting only
> on this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GalSim-developers/GalSim/issues/661#issuecomment-107773457>
> .
>


-- 
Regards

Arun Kannawadi Jayaraman
PhD candidate, Dept. of Physics,
Carnegie Mellon University,
Pittsburgh, PA 15213

**Comment by rmandelb** [comment]
Even when we have something like an Airy, the MTF can be 10^-6 or 10^-8 where it should be zero due to numerical artifacts.  Surely at some point a nonzero value is low enough that it doesn't matter?

@chazshapiro, can you give us a more clear statement on the requirements?

In any case, this is about more than IMCOM.  For precise work that doesn't involve IMCOM, one might want to have a better representation of the PSF, so this change will still be beneficial.

**Comment by chazshapiro** [comment]
The mostly Airy MTF we've used for PPL, which has a sampling factor similar
to WFIRST H-band, has some numerical artifacts outside the bandlimit that
are O(10^-5).  For frequencies about 50% above the bandlimit, the errors
are O(10^-6) or smaller.  I'm not saying that's the requirement -
unfortunately, what IMCOM can handle is a matter of trial and error at this
point.  But a good guess would be a 10^-5 limit.

Let me know if you think we need to prioritize changing IMCOM to enforce
the bandlimit itself - I need to leave this issue be unless it becomes
pressing.  But even though this change will allow IMCOM to construct a
valid solution from non-ideal PSF input, the images themselves would still
contain the spurious high frequencies at some level.  Shape measurement
accuracy on the oversampled images would need to be verified.

Chaz



---

**Comment by barnabytprowe** [comment]
Hi guys!  This one I really felt I had to weigh in on, as it's directly involving two former projects of mine.  I haven't digested all of the above (indeed I only just got alerted to this question when I saw Chaz's response) but I am going to think about it and get back ASAP.

@chazshapiro : if it comes down to the fact that the best thing to do is make IMCOM forcibly filter all input PSFs to be strictly bandlimited I can do that.  It will probably be quickest if I do it, I know that rusty old Fortran 95 pretty well, although I'd estimate about two weeks.  I'd need to iterate with you about your preferred user interface for specifying the bandlimit to IMCOM.

But it might not be necessary.  I'd say shooting from the hip that 10-4 was kind of on the edge of tolerable even being quite conservative, but the artifacts are quite e1-ish.  And the problem is that because IMCOM is partly aimed at exploring what sampling you can get at the very limit of what's possible, given your PSF, these sorts of details matter.  As Chaz says it's not trivial from the outset to say in advance which effects will matter.

I'll look properly into it and get back to you all!

**Comment by barnabytprowe** [comment]
(We can take some solace in the fact that having spurious high frequency stuff in the PSF only makes sampling harder in an IMCOM test of image reconstruction, and so some amount of contamination in this direction will make us slightly conservative rather than optimistic.  That's good.  But being too conservative is inefficient, so it's worth getting this right.)

**Comment by chazshapiro** [comment]
Nice... we're putting the band back together.

I already modified IMCOM in a hard-coded way to set the input MTFs to zero
above some frequency u_max (changing u_max requires re-compiling).  Maybe
it only needed to be done in the target PSF though.  Promoting u_max to be
user-specified will be the more laborious task.

---

**Comment by barnabytprowe** [comment]
Just like old times ;)

>I already modified IMCOM in a hard-coded way to set the input MTFs to zero
above some frequency u_max (changing u_max requires re-compiling). 

Ah, cool!

> Maybe it only needed to be done in the target PSF though.

That's possibly true, but actually I think it's most conservative to do it on both input and target PSFs.  Those artifacts at high frequency in the MTF would be extra image information if they were really present, so it's best not to lead IMCOM into thinking they are available.   (If it thinks they are available, IMCOM will find a solution that smooths them down to lower frequency modes so as to minimize noise in the reconstructed image, and will report slightly better output noise statistics as a consequence!)

@rmandelb : (hi Rachel!) where can I find the script used to make the images above?  I think it's called MTF_analysis or similar.  I would like to have a play, as I'm a little rusty thinking in Fourier land.

Here is what I am thinking though:

* It would be great to get those artifacts down below 10^-4 beyond the bandlimit I think.  This should be pretty much safe for most purposes I would say.  Looks to me like we're only a factor 3-5 short of that goal as things stand.

* For `approximate_struts = true` increasing the oversampling helps as it should: it zero pads the pupil image in the angular frequency domain and so moves those aliased ghost remnants of the MTF further 'off screen'.  Boosting the `pad_factor` might also help as this increases the *resolution* of the pupil plane image - useful e.g. if struts are only a few pixels thin and so their shape is blockily distorted, or for reducing up some of the green cross effect which I think due to the representation of a curved pupil edge as a series of straight, hard, perpendicular edges.  Both params combine to increase the underlying `InterpolatedImage` size though, of course, but there might be a "sweet spot" combination of the two that differs from the one you tried a little (although probably not by much).

* For `approximate_struts = false` I'm aware the pupil plane image itself can't be made higher resolution.  But if you hit a performance wall increasing `pad_factor` or `oversampling`, then one more ambitious thing that could be considered might be to allow the pupil plane used in the `OpticalPSF` to take values in the range [0, 1] rather than forcing it to be a Boolean.

For this last point, the aim would be to get the LHS image rather than the RHS:

![](http://www.cs.sfu.ca/CourseCentral/166/johnwill/_images/smoothUnSmoothCircles.png)

(from here: http://www.cs.sfu.ca/CourseCentral/166/johnwill/coordinates.html)

This is "anti-aliasing" and it's a cheap way of reducing these artifacts.  It would definitely help with the green crosses in the images above.   But it would of course come at the expense of fidelity - by adding a slight additional smoothing to the pupil plane edges I think we would be effectively adding a spurious multiplicative window function to our real space PSF.  If the anti-aliasing in the pupil plane were light enough the window would be so broad as to not impact science appreciably (e.g. doing a super cheap shift and add convolution in the pupil plane *might well* correspond to a window in real space that is many arcsec broad, making it a suitable short cut.  I'd need to check though!)

**Comment by barnabytprowe** [comment]
comment above edited in Github!

**Comment by barnabytprowe** [comment]
Here's a slightly more informative site for the sort of cheap, shift+add, compact kernel smoothing I might suggest: http://www.cyanogen.com/help/maximdl/Low-Pass_Filtering.htm.  The kernel I'd suggest would be:

1/16 1/8 1/16
1/8 1/4 1/8
1/16 1/8 1/16

...as I think I know how to write this analytically in wavefront space and real PSF space using sinc^2 and sinc^4 functions. I could thus calculate the size of the effective window to see if it troubles us (I think it wouldn't).  An idea anyhow.  Right must sleep!

**Comment by rmandelb** [comment]
Barney!  Blast from the past!

Sorry for this slightly scattered response; I've been running a conference all day ( https://twitter.com/hashtag/cosmomlstat?vertical=default&f=tweets ) and am having trouble readjusting my brain or in fact getting it to work at all. 

> where can I find the script used to make the images above?

It's in @arunkannawadi 's private repository.  If he wants to add you, hopefully he will do that and then you can access any updates in the versions.  But I'll e-mail you the script in a moment so you at least see what it looks like now.  I'm happy to see what you might find if you play around.

 For ```approximate_struts=False```, I have it doing this kludgy zero-padding around the edges of the pupil plane image to get higher accuracy.  But the image is already very large so I am reluctant to do that by more than a factor of 2 (as is, this higher accuracy calculation takes nearly 8GB RAM!).

Your idea of a pupil plane image that isn't just 0 or 1 is intriguing.

**Comment by arunkannawadi** [comment]
It's in @arunkannawadi <https://github.com/arunkannawadi> 's private
repository. If he wants to add you, hopefully he will do that and then you
can access any updates in the versions. But I'll e-mail you the script in a
moment so you at least see what it looks like now. I'm happy to see what
you might find if you play around.
Sorry, I wasn't following this thread yesterday. I see that Rachel has
already sent you the script and that is updated. The other files in that
private repo are not related to the accuracy parameters of the WFIRST PSF,
so the script that Rachel sent should do I guess. Or should I put the
script somewhere here in GalSim repo so other people can have a look at it,
if interested?
—

Reply to this email directly or view it on GitHub
<https://github.com/GalSim-developers/GalSim/issues/661#issuecomment-108658721>
.



-- 
Regards

Arun Kannawadi Jayaraman
PhD candidate, Dept. of Physics,
Carnegie Mellon University,
Pittsburgh, PA 15213

**Comment by rmandelb** [comment]
> Or should I put the script somewhere here in GalSim repo so other people can have a look at it, 
> if interested?

Let's see if anyone else is interested (the subset of people who will want to play with it in detail probably already has access to the script?).  Since it doesn't follow GalSim coding standards and has extra dependencies, it would need to go in devel/external/ on the #661 branch if it goes in.

**Comment by barnabytprowe** [comment]
Apologies for the radio silence - I had a deadline creep up on me hard in my other life!  I'm flying long haul tomorrow though so will have a good chunk of time to work on this then, will get back v. soon.

**Comment by rmandelb** [comment]
Closing #661.
